version: '2.2'
services:
  service-irango-payment-api:
    container_name: service-irango-payment-api
    cpus: 2
    mem_limit: 2000m
    environment:
      - NODE_ENV=development
    networks:
      - local-network
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3002:3002
    volumes:
      - .:/app # to sync code changes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3002/health-check"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  local-network:
    name: local-network
    external: true
